# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Software/ZYBO_Master.xdc

# Block Designs: bd/test_cmd/test_cmd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_cmd || ORIG_REF_NAME==test_cmd}]

# IP: bd/test_cmd/ip/test_cmd_processing_system7_0_0/test_cmd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_cmd_processing_system7_0_0 || ORIG_REF_NAME==test_cmd_processing_system7_0_0}]

# IP: bd/test_cmd/ip/test_cmd_processing_system7_0_axi_periph_1/test_cmd_processing_system7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_cmd_processing_system7_0_axi_periph_1 || ORIG_REF_NAME==test_cmd_processing_system7_0_axi_periph_1}]

# IP: bd/test_cmd/ip/test_cmd_rst_processing_system7_0_100M_1/test_cmd_rst_processing_system7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_cmd_rst_processing_system7_0_100M_1 || ORIG_REF_NAME==test_cmd_rst_processing_system7_0_100M_1}]

# IP: bd/test_cmd/ip/test_cmd_motor_0_0/test_cmd_motor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_cmd_motor_0_0 || ORIG_REF_NAME==test_cmd_motor_0_0}]

# IP: bd/test_cmd/ip/test_cmd_motor_1_0/test_cmd_motor_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_cmd_motor_1_0 || ORIG_REF_NAME==test_cmd_motor_1_0}]

# IP: bd/test_cmd/ip/test_cmd_xbar_0/test_cmd_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_cmd_xbar_0 || ORIG_REF_NAME==test_cmd_xbar_0}]

# IP: bd/test_cmd/ip/test_cmd_auto_pc_0/test_cmd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_cmd_auto_pc_0 || ORIG_REF_NAME==test_cmd_auto_pc_0}]

# XDC: bd/test_cmd/ip/test_cmd_processing_system7_0_0/test_cmd_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_cmd_processing_system7_0_0 || ORIG_REF_NAME==test_cmd_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/test_cmd/ip/test_cmd_rst_processing_system7_0_100M_1/test_cmd_rst_processing_system7_0_100M_1_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_cmd_rst_processing_system7_0_100M_1 || ORIG_REF_NAME==test_cmd_rst_processing_system7_0_100M_1}]

# XDC: bd/test_cmd/ip/test_cmd_rst_processing_system7_0_100M_1/test_cmd_rst_processing_system7_0_100M_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_cmd_rst_processing_system7_0_100M_1 || ORIG_REF_NAME==test_cmd_rst_processing_system7_0_100M_1}]

# XDC: bd/test_cmd/ip/test_cmd_rst_processing_system7_0_100M_1/test_cmd_rst_processing_system7_0_100M_1_ooc.xdc

# XDC: bd/test_cmd/ip/test_cmd_xbar_0/test_cmd_xbar_0_ooc.xdc

# XDC: bd/test_cmd/ip/test_cmd_auto_pc_0/test_cmd_auto_pc_0_ooc.xdc

# XDC: bd/test_cmd/test_cmd_ooc.xdc
