# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Travail/Objets/GitHub/Silver/Software/Cmd_motor/Cmd_motor.cache/wt [current_project]
set_property parent.project_path C:/Travail/Objets/GitHub/Silver/Software/Cmd_motor/Cmd_motor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/travail/objets/github/silver/software/ip_repo/encoder_1.0
  c:/travail/objets/github/silver/software/ip_repo/speed_1.0
  c:/travail/objets/github/silver/software/ip_repo/servo_1.0
  c:/Travail/Objets/GitHub/Silver/Software/ip_repo/motor_1.0
  c:/travail/objets/github/silver/software/ip_repo/pwm_1.0
  c:/Travail/Objets/GitHub/Silver/Software/ip_repo
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files C:/Travail/Objets/GitHub/Silver/Software/Cmd_motor/Cmd_motor.srcs/sources_1/bd/test_cmd/test_cmd.bd
set_property used_in_implementation false [get_files -all c:/Travail/Objets/GitHub/Silver/Software/Cmd_motor/Cmd_motor.srcs/sources_1/bd/test_cmd/ip/test_cmd_processing_system7_0_0/test_cmd_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Travail/Objets/GitHub/Silver/Software/Cmd_motor/Cmd_motor.srcs/sources_1/bd/test_cmd/ip/test_cmd_rst_processing_system7_0_100M_1/test_cmd_rst_processing_system7_0_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Travail/Objets/GitHub/Silver/Software/Cmd_motor/Cmd_motor.srcs/sources_1/bd/test_cmd/ip/test_cmd_rst_processing_system7_0_100M_1/test_cmd_rst_processing_system7_0_100M_1.xdc]
set_property used_in_implementation false [get_files -all c:/Travail/Objets/GitHub/Silver/Software/Cmd_motor/Cmd_motor.srcs/sources_1/bd/test_cmd/ip/test_cmd_rst_processing_system7_0_100M_1/test_cmd_rst_processing_system7_0_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Travail/Objets/GitHub/Silver/Software/Cmd_motor/Cmd_motor.srcs/sources_1/bd/test_cmd/ip/test_cmd_xbar_0/test_cmd_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Travail/Objets/GitHub/Silver/Software/Cmd_motor/Cmd_motor.srcs/sources_1/bd/test_cmd/ip/test_cmd_auto_pc_0/test_cmd_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Travail/Objets/GitHub/Silver/Software/Cmd_motor/Cmd_motor.srcs/sources_1/bd/test_cmd/test_cmd_ooc.xdc]
set_property is_locked true [get_files C:/Travail/Objets/GitHub/Silver/Software/Cmd_motor/Cmd_motor.srcs/sources_1/bd/test_cmd/test_cmd.bd]

read_vhdl -library xil_defaultlib C:/Travail/Objets/GitHub/Silver/Software/Cmd_motor/Cmd_motor.srcs/sources_1/bd/test_cmd/hdl/test_cmd_wrapper.vhd
read_xdc C:/Travail/Objets/GitHub/Silver/Software/Cmd_motor/Cmd_motor.srcs/constrs_1/imports/Software/ZYBO_Master.xdc
set_property used_in_implementation false [get_files C:/Travail/Objets/GitHub/Silver/Software/Cmd_motor/Cmd_motor.srcs/constrs_1/imports/Software/ZYBO_Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top test_cmd_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef test_cmd_wrapper.dcp
catch { report_utilization -file test_cmd_wrapper_utilization_synth.rpt -pb test_cmd_wrapper_utilization_synth.pb }
