# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Travail/Objets/GitHub/Silver/Software/GP2/GP2.cache/wt [current_project]
set_property parent.project_path C:/Travail/Objets/GitHub/Silver/Software/GP2/GP2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files C:/Travail/Objets/GitHub/Silver/Software/GP2/GP2.srcs/sources_1/bd/test_gp2/test_gp2.bd
set_property used_in_implementation false [get_files -all c:/Travail/Objets/GitHub/Silver/Software/GP2/GP2.srcs/sources_1/bd/test_gp2/ip/test_gp2_processing_system7_0_0/test_gp2_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Travail/Objets/GitHub/Silver/Software/GP2/GP2.srcs/sources_1/bd/test_gp2/ip/test_gp2_rst_processing_system7_0_100M_0/test_gp2_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Travail/Objets/GitHub/Silver/Software/GP2/GP2.srcs/sources_1/bd/test_gp2/ip/test_gp2_rst_processing_system7_0_100M_0/test_gp2_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Travail/Objets/GitHub/Silver/Software/GP2/GP2.srcs/sources_1/bd/test_gp2/ip/test_gp2_rst_processing_system7_0_100M_0/test_gp2_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Travail/Objets/GitHub/Silver/Software/GP2/GP2.srcs/sources_1/bd/test_gp2/ip/test_gp2_xadc_wiz_0_1/test_gp2_xadc_wiz_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Travail/Objets/GitHub/Silver/Software/GP2/GP2.srcs/sources_1/bd/test_gp2/ip/test_gp2_xadc_wiz_0_1/test_gp2_xadc_wiz_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Travail/Objets/GitHub/Silver/Software/GP2/GP2.srcs/sources_1/bd/test_gp2/ip/test_gp2_auto_pc_0/test_gp2_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Travail/Objets/GitHub/Silver/Software/GP2/GP2.srcs/sources_1/bd/test_gp2/test_gp2_ooc.xdc]
set_property is_locked true [get_files C:/Travail/Objets/GitHub/Silver/Software/GP2/GP2.srcs/sources_1/bd/test_gp2/test_gp2.bd]

read_vhdl -library xil_defaultlib C:/Travail/Objets/GitHub/Silver/Software/GP2/GP2.srcs/sources_1/bd/test_gp2/hdl/test_gp2_wrapper.vhd
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top test_gp2_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef test_gp2_wrapper.dcp
catch { report_utilization -file test_gp2_wrapper_utilization_synth.rpt -pb test_gp2_wrapper_utilization_synth.pb }
