# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Software/ZYBO_Master.xdc

# Block Designs: bd/test_asserv/test_asserv.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_asserv || ORIG_REF_NAME==test_asserv}]

# IP: bd/test_asserv/ip/test_asserv_processing_system7_0_0/test_asserv_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_asserv_processing_system7_0_0 || ORIG_REF_NAME==test_asserv_processing_system7_0_0}]

# IP: bd/test_asserv/ip/test_asserv_processing_system7_0_axi_periph_0/test_asserv_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_asserv_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==test_asserv_processing_system7_0_axi_periph_0}]

# IP: bd/test_asserv/ip/test_asserv_rst_processing_system7_0_100M_0/test_asserv_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_asserv_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==test_asserv_rst_processing_system7_0_100M_0}]

# IP: bd/test_asserv/ip/test_asserv_xbar_0/test_asserv_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_asserv_xbar_0 || ORIG_REF_NAME==test_asserv_xbar_0}]

# IP: bd/test_asserv/ip/test_asserv_encoder_0_3/test_asserv_encoder_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_asserv_encoder_0_3 || ORIG_REF_NAME==test_asserv_encoder_0_3}]

# IP: bd/test_asserv/ip/test_asserv_encoder_1_0/test_asserv_encoder_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_asserv_encoder_1_0 || ORIG_REF_NAME==test_asserv_encoder_1_0}]

# IP: bd/test_asserv/ip/test_asserv_motor_0_0/test_asserv_motor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_asserv_motor_0_0 || ORIG_REF_NAME==test_asserv_motor_0_0}]

# IP: bd/test_asserv/ip/test_asserv_motor_1_0/test_asserv_motor_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_asserv_motor_1_0 || ORIG_REF_NAME==test_asserv_motor_1_0}]

# IP: bd/test_asserv/ip/test_asserv_auto_pc_0/test_asserv_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_asserv_auto_pc_0 || ORIG_REF_NAME==test_asserv_auto_pc_0}]

# XDC: bd/test_asserv/ip/test_asserv_processing_system7_0_0/test_asserv_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_asserv_processing_system7_0_0 || ORIG_REF_NAME==test_asserv_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/test_asserv/ip/test_asserv_rst_processing_system7_0_100M_0/test_asserv_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_asserv_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==test_asserv_rst_processing_system7_0_100M_0}]

# XDC: bd/test_asserv/ip/test_asserv_rst_processing_system7_0_100M_0/test_asserv_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_asserv_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==test_asserv_rst_processing_system7_0_100M_0}]

# XDC: bd/test_asserv/ip/test_asserv_rst_processing_system7_0_100M_0/test_asserv_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/test_asserv/ip/test_asserv_xbar_0/test_asserv_xbar_0_ooc.xdc

# XDC: bd/test_asserv/ip/test_asserv_auto_pc_0/test_asserv_auto_pc_0_ooc.xdc

# XDC: bd/test_asserv/test_asserv_ooc.xdc
